/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CondicoesRouteImport } from './routes/condicoes'
import { Route as DireitosRouteImport } from './routes/direitos'
import { Route as EmDisputaRouteImport } from './routes/em-disputa'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as ApiPublicTseIngestRouteImport } from './routes/api/public/tse/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesRoute = CondicoesRouteImport.update({
  id: '/condicoes',
  path: '/condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitosRoute = DireitosRouteImport.update({
  id: '/direitos',
  path: '/direitos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmDisputaRoute = EmDisputaRouteImport.update({
  id: '/em-disputa',
  path: '/em-disputa',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTseIngestRoute = ApiPublicTseIngestRouteImport.update({
  id: '/api/public/tse/ingest',
  path: '/api/public/tse/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/direitos': typeof DireitosRoute
  '/em-disputa': typeof EmDisputaRoute
  '/metodo': typeof MetodoRoute
  '/api/public/tse/ingest': typeof ApiPublicTseIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/direitos': typeof DireitosRoute
  '/em-disputa': typeof EmDisputaRoute
  '/metodo': typeof MetodoRoute
  '/api/public/tse/ingest': typeof ApiPublicTseIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/direitos': typeof DireitosRoute
  '/em-disputa': typeof EmDisputaRoute
  '/metodo': typeof MetodoRoute
  '/api/public/tse/ingest': typeof ApiPublicTseIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/condicoes'
    | '/direitos'
    | '/em-disputa'
    | '/metodo'
    | '/api/public/tse/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/condicoes'
    | '/direitos'
    | '/em-disputa'
    | '/metodo'
    | '/api/public/tse/ingest'
  id:
    | '__root__'
    | '/'
    | '/condicoes'
    | '/direitos'
    | '/em-disputa'
    | '/metodo'
    | '/api/public/tse/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CondicoesRoute: typeof CondicoesRoute
  DireitosRoute: typeof DireitosRoute
  EmDisputaRoute: typeof EmDisputaRoute
  MetodoRoute: typeof MetodoRoute
  ApiPublicTseIngestRoute: typeof ApiPublicTseIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes': {
      id: '/condicoes'
      path: '/condicoes'
      fullPath: '/condicoes'
      preLoaderRoute: typeof CondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direitos': {
      id: '/direitos'
      path: '/direitos'
      fullPath: '/direitos'
      preLoaderRoute: typeof DireitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-disputa': {
      id: '/em-disputa'
      path: '/em-disputa'
      fullPath: '/em-disputa'
      preLoaderRoute: typeof EmDisputaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tse/ingest': {
      id: '/api/public/tse/ingest'
      path: '/api/public/tse/ingest'
      fullPath: '/api/public/tse/ingest'
      preLoaderRoute: typeof ApiPublicTseIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CondicoesRoute: CondicoesRoute,
  DireitosRoute: DireitosRoute,
  EmDisputaRoute: EmDisputaRoute,
  MetodoRoute: MetodoRoute,
  ApiPublicTseIngestRoute: ApiPublicTseIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
