/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CondicoesRouteImport } from './routes/condicoes'
import { Route as EmDisputaRouteImport } from './routes/em-disputa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesRoute = CondicoesRouteImport.update({
  id: '/condicoes',
  path: '/condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmDisputaRoute = EmDisputaRouteImport.update({
  id: '/em-disputa',
  path: '/em-disputa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/em-disputa': typeof EmDisputaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/em-disputa': typeof EmDisputaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/condicoes': typeof CondicoesRoute
  '/em-disputa': typeof EmDisputaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/condicoes' | '/em-disputa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/condicoes' | '/em-disputa'
  id: '__root__' | '/' | '/condicoes' | '/em-disputa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CondicoesRoute: typeof CondicoesRoute
  EmDisputaRoute: typeof EmDisputaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes': {
      id: '/condicoes'
      path: '/condicoes'
      fullPath: '/condicoes'
      preLoaderRoute: typeof CondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-disputa': {
      id: '/em-disputa'
      path: '/em-disputa'
      fullPath: '/em-disputa'
      preLoaderRoute: typeof EmDisputaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CondicoesRoute: CondicoesRoute,
  EmDisputaRoute: EmDisputaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
